blueprint:
  name: Gesture — N toggles in M seconds → run scene
  description: >
    Counts on/off flips of an entity within a time window and runs a scene when the threshold is reached.
  domain: automation
  input:
    trigger_entity:
      name: Entity to monitor for flips
      description: Any on/off capable entity (light, switch, fan, etc.)
      selector:
        entity: {}
    count_threshold:
      name: Number of flips required
      default: 3
      selector:
        number:
          min: 2
          max: 20
          step: 1
          mode: box
    window_seconds:
      name: Window (seconds)
      default: 10
      selector:
        number:
          min: 1
          max: 60
          step: 1
          mode: box
    scene_target:
      name: Scene to run
      selector:
        entity:
          domain: scene