blueprint:
  name: Find My Apple Device
  description: Automate find my apple device using icloud integration.
  domain: script
  source_url: https://gist.github.com/ggoulart/fdfd3a378c3a6b06acdf2e7aeca955d7
  author: https://gist.github.com/ggoulart
  input:
    apple_device:
      name: Apple device
      description: Apple device to be found.
      selector:
        device:
          filter:
          - integration: icloud
          multiple: false
    apple_account:
      name: Apple account email
      description: Apple account email linked to device.
      default: email@here.com
      selector:
        text:
          multiple: false
          multiline: false
mode: single
sequence:
- alias: Set up variables
  variables:
    device_id: !input apple_device
    device_name: '{{ device_attr(device_id, "name") }}

      '
- alias: Find Device
  service: icloud.play_sound
  data:
    account: !input apple_account
    device_name: '{{ device_name }}'
